# Generated by Django 4.1.7 on 2023-03-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redirect", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShorterLink",
            new_name="ShortnerLink",
        ),
    ]
