# Generated by Django 4.1.7 on 2023-04-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("redirect", "0002_rename_shorterlink_shortnerlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complete_link",
                    models.CharField(max_length=200, verbose_name="لینک کامل"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_link",
                    models.CharField(max_length=20, verbose_name="لینک کوتاه شده"),
                ),
                (
                    "full_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redirect.fulllink",
                        verbose_name="لینک کامل",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
    ]
