# Generated by Django 4.1.7 on 2023-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirect", "0003_fulllink_shortlink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShortnerLink",
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="short_link",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="لینک کوتاه شده"
            ),
        ),
    ]
