# Generated by Django 4.1.7 on 2023-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirect", "0004_delete_shortnerlink_alter_shortlink_short_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fulllink",
            options={
                "verbose_name": "لینک کامل",
                "verbose_name_plural": "لینک های کامل",
            },
        ),
        migrations.AlterModelOptions(
            name="shortlink",
            options={
                "verbose_name": "لینک کوتاه",
                "verbose_name_plural": "لینک های کوتاه",
            },
        ),
        migrations.AlterField(
            model_name="fulllink",
            name="complete_link",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="لینک کامل"
            ),
        ),
    ]
